### ISSUE TITLE
WebTorrent silently set itself as default magnet/torrent handler

### ISSUE THREAD

**Issue by diimdeep** [feross/webtorrent-desktop#367]
**What version of WebTorrent Desktop?**
0.3.3

**What operating system and version?**
OSX 10.11

**What did you do?**
Open app

**What did you expect to happen?**
App should not silently modify user settings

**What actually happened?**
WebTorrent silently set itself as default magnet handler

**Comment by feross** [comment]
Agree. We wanted to get magnet link handling working first. Planning to add an option once we have a prefs window.

**Comment by kristofferR** [comment]
This really needs to be a blocking issue for v.0.6.1, and it shouldn't be too hard to fix now that the preference panel is there.

I understand that it's not intentionally malicious, but right now this feels kinda malware-ish. Applications you install shouldn't change system settings like default home page or magnet handler without asking first, and especially set it at every launch of the application. 

I can't keep Webtorrent installed until this is fixed.

**Comment by feross** [comment]
@kristofferR I feel your pain and agree with you. We're working as fast as we can to fix issues. This should be fixed pretty soon.

**Comment by quicoto** [comment]
Same here. I didn't know what was happening until I realised it was WebTorrent :)

Has to uninstall for now. I will install again this magic app when this gets fixed.

Thank you very much!

**Comment by skirankumars31** [comment]
I was so pissed off when webtorrent set itself as the default Application for opening the magnet links. I just wanted to try it before setting it as my default torrent app. Felt like a malware

**Comment by diimdeep** [comment]
I don't understand why this is not yet fixed, it was reported ages ago.

**Comment by dcposch** [comment]
Will be fixed in the next version
